export const SET_DATA_RAP = 'SET_DATA_RAP';
export const SET_DATA_CUM_RAP_THEO_HE_THONG = 'SET_DATA_CUM_RAP_THEO_HE_THONG';
export const RAP_THEO_CUM_RAP = 'RAP_THEO_CUM_RAP';
export const SET_DATA_CUM_RAP = 'SET_DATA_CUM_RAP';
export const SET_DATA_LICH_CHIEU = 'SET_DATA_LICH_CHIEU';
export const SET_CHI_TIET_PHIM = 'SET_CHI_TIET_PHIM';